# Generated by Django 3.1.1 on 2020-11-13 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=15, unique=True)),
                ('unique_id', models.IntegerField(blank=True)),
                ('at_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('at_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='area_travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_no', models.CharField(max_length=10)),
                ('from_area_id', models.IntegerField(blank=True)),
                ('to_area_id', models.IntegerField(blank=True)),
                ('from_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('from_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('to_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('to_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('booking_time', models.DateTimeField(default=datetime.datetime.now)),
                ('online_booking', models.BooleanField()),
                ('mobile_site_booking', models.BooleanField()),
                ('car_cancellation', models.CharField(blank=True, choices=[('0', '0'), ('1', '1')], max_length=20)),
                ('from_date', models.DateTimeField(default=datetime.datetime.now)),
                ('to_date', models.DateTimeField(default=datetime.datetime.now)),
                ('package_id', models.CharField(blank=True, choices=[('4&40', '1'), ('8&80', '2'), ('6&60', '3'), ('10&100', '4'), ('5&50', '5'), ('3&30', '6'), ('12&120', '7')], max_length=20)),
                ('travel_type', models.CharField(blank=True, choices=[('long distance', '1'), ('point to point', '2'), ('hourly rental', '3')], max_length=50)),
                ('vehicle_type', models.CharField(blank=True, choices=[('SEDAN', '1'), ('COUPE', '2'), ('SPORTS CAR', '3'), ('HATCHBACK', '4'), ('SPORT-UTILITY VEHICLE', '5')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=15, unique=True)),
                ('unique_id', models.IntegerField(blank=True)),
                ('at_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('at_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='city_travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_no', models.CharField(max_length=10)),
                ('from_city_id', models.IntegerField(blank=True)),
                ('to_city_id', models.IntegerField(blank=True)),
                ('from_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9)),
                ('from_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9)),
                ('to_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9)),
                ('to_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9)),
                ('booking_time', models.DateTimeField(default=datetime.datetime.now)),
                ('online_booking', models.BooleanField()),
                ('mobile_site_booking', models.BooleanField()),
                ('car_cancellation', models.CharField(blank=True, choices=[('0', '0'), ('1', '1')], max_length=20)),
                ('from_date', models.DateTimeField(default=datetime.datetime.now)),
                ('to_date', models.DateTimeField(default=datetime.datetime.now)),
                ('package_id', models.CharField(blank=True, choices=[('4&40', '1'), ('8&80', '2'), ('6&60', '3'), ('10&100', '4'), ('5&50', '5'), ('3&30', '6'), ('12&120', '7')], max_length=20)),
                ('travel_type', models.CharField(blank=True, choices=[('long distance', '1'), ('point to point', '2'), ('hourly rental', '3')], max_length=50)),
                ('vehicle_type', models.CharField(blank=True, choices=[('SEDAN', '1'), ('COUPE', '2'), ('SPORTS CAR', '3'), ('HATCHBACK', '4'), ('SPORT-UTILITY VEHICLE', '5')], max_length=50)),
            ],
        ),
    ]
